### ISSUE TITLE
Playground does not work

### ISSUE THREAD

**Issue by TheDutchCoder** [unjs/unimport#121]
Disclaimer: this is using `npm`.

When trying to run the playground (after an `npm i`), the server throws the following error:
```
[plugin:unimport] s.hasChanged is not a function
/Users/reinierkaper/personal/unimport/playground/src/main.ts
    at TransformContext.transform (file:///Users/reinierkaper/personal/unimport/playground/vite.config.ts.timestamp-1663630386798.mjs:1067:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/reinierkaper/personal/unimport/playground/node_modules/vite-plugin-inspect/dist/index.mjs:676:23
    at async Object.transform (file:///Users/reinierkaper/personal/unimport/playground/node_modules/vite/dist/node/chunks/dep-557f29e6.js:41102:30)
    at async loadAndTransform (file:///Users/reinierkaper/personal/unimport/playground/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37364:29
```

System: MacOS 12.5.1
Browser: Chrome 105.0.5195.125
Node: 16.15.1
npm: 8.12.1

**Comment by antfu** [comment]
In this repo you have to use pnpm to setup the dev env.

**Comment by TheDutchCoder** [comment]
Ah ok, no worries, I thought pnpm and npm were interchangeable. I will look into it!
