### ISSUE TITLE
Nuxt: useHead undefined after initiating a regex (since monday) 

### ISSUE THREAD

**Issue by hankdetank** [unjs/unimport#346]
### Environment

Linux (this problem doesnt appear to happen on windows).
tested on different node versions.

### Reproduction

https://stackblitz.com/edit/github-819pq2-4sknkq?file=layouts%2Fdefault.vue

### Describe the bug

"var emailregexx =
/^[a-zA-Z0-9.!#$%&'+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)$/;
useHead({
meta: [
{
name: 'viewport',
content:
'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0',
},
],
});"

This code crashes. And my question is why.
I've created an issue on nuxt at: https://github.com/nuxt/nuxt/issues/27392 . There danielroe asked me to created to ticket here.

It happens since monday(maybe friday or thursday) and this code is already years old.

When you remove the regex line, all works normally again.

When you change the regex to the following 2 options it works:
/^[a-zA-Z0-9.!#$%&'*+/?{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/; (removed the `)

/^[a-zA-Z0-9.!#$%&'*+\\/?`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/; (escaped the /)

### Additional context

Error that gets thrown:
useHead is not defined

at _sfc_main.setup (./layouts/default.js:42:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:195:19)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7572:25)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7533:36)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:15)
at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:755:14)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:7)
at eval (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:639:25)
at async unrollBuffer$1 (./node_modules/@vue/s

**Comment by manniL** [comment]
@hankdetank please provide an unimport-only reproduction next time 😋

[Example (using only unimport here)](https://stackblitz.com/edit/unimport-346?file=vite.config.ts,src%2FApp.vue,composables%2Fvanilla.js) reproduction in this case

**Comment by noootwo** [comment]
This appears to be an issue with the upstream, and the error will occur at this step:
https://github.com/unjs/unimport/blob/b2db6fec8bb58a405a23d7f72dfd652614bc8017/src/regexp.ts#L31 `stripLiteral` return an incorrect result, it stripped a part of the regular expression.

And here is a [workaround](https://stackblitz.com/edit/unimport-346-va2mdh?file=vite.config.ts,src%2FApp.vue,src%2Fmain.ts), replace this regex to ```/^[a-zA-Z0-9.!#$%&'+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)$/```
